[[main]]
  name = "Research"
  url = "/research/"
  weight = 1
[[main]]
  name = "Outputs"
  url = "/outputs/"
  weight = 2
[[main]]
  name = "People"
  url = "/team/"
  weight = 3
[[main]]
  name = "About OJ"
  url = "/about/"
  weight = 4
[[main]]
  name = "Contact"
  url = "/contact/"
  weight = 5
